# Generated by Django 4.2.1 on 2023-06-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squiggle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='user',
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_data',
            field=models.TextField(),
        ),
    ]
