# Generated by Django 4.2.1 on 2023-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squiggle', '0002_remove_drawing_user_alter_drawing_drawing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
